// PlantVillage veri setinin standart 38 sınıfı ve Türkçe karşılıkları.
// Kaynak sınıf isimleri: https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset
export const PLANTVILLAGE_CLASSES_TR: Record<string, { tr: string; plant: string; healthy: boolean }> = {
  "Apple___Apple_scab": { tr: "Elma Karalekesi", plant: "Elma", healthy: false },
  "Apple___Black_rot": { tr: "Elma Kara Çürüklüğü", plant: "Elma", healthy: false },
  "Apple___Cedar_apple_rust": { tr: "Elma Pas Hastalığı", plant: "Elma", healthy: false },
  "Apple___healthy": { tr: "Sağlıklı", plant: "Elma", healthy: true },
  "Blueberry___healthy": { tr: "Sağlıklı", plant: "Yaban Mersini", healthy: true },
  "Cherry_(including_sour)___Powdery_mildew": { tr: "Kiraz Külleme Hastalığı", plant: "Kiraz", healthy: false },
  "Cherry_(including_sour)___healthy": { tr: "Sağlıklı", plant: "Kiraz", healthy: true },
  "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": { tr: "Mısır Gri Yaprak Lekesi", plant: "Mısır", healthy: false },
  "Corn_(maize)___Common_rust_": { tr: "Mısır Pas Hastalığı", plant: "Mısır", healthy: false },
  "Corn_(maize)___Northern_Leaf_Blight": { tr: "Mısır Kuzey Yaprak Yanıklığı", plant: "Mısır", healthy: false },
  "Corn_(maize)___healthy": { tr: "Sağlıklı", plant: "Mısır", healthy: true },
  "Grape___Black_rot": { tr: "Üzüm Kara Çürüklüğü", plant: "Üzüm", healthy: false },
  "Grape___Esca_(Black_Measles)": { tr: "Üzüm Esca (Kara Çiçek) Hastalığı", plant: "Üzüm", healthy: false },
  "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": { tr: "Üzüm Yaprak Yanıklığı", plant: "Üzüm", healthy: false },
  "Grape___healthy": { tr: "Sağlıklı", plant: "Üzüm", healthy: true },
  "Orange___Haunglongbing_(Citrus_greening)": { tr: "Turunçgil Yeşillenme Hastalığı (HLB)", plant: "Portakal", healthy: false },
  "Peach___Bacterial_spot": { tr: "Şeftali Bakteriyel Leke", plant: "Şeftali", healthy: false },
  "Peach___healthy": { tr: "Sağlıklı", plant: "Şeftali", healthy: true },
  "Pepper,_bell___Bacterial_spot": { tr: "Biber Bakteriyel Leke", plant: "Biber", healthy: false },
  "Pepper,_bell___healthy": { tr: "Sağlıklı", plant: "Biber", healthy: true },
  "Potato___Early_blight": { tr: "Patates Erken Yanıklık", plant: "Patates", healthy: false },
  "Potato___Late_blight": { tr: "Patates Geç Yanıklık", plant: "Patates", healthy: false },
  "Potato___healthy": { tr: "Sağlıklı", plant: "Patates", healthy: true },
  "Raspberry___healthy": { tr: "Sağlıklı", plant: "Ahududu", healthy: true },
  "Soybean___healthy": { tr: "Sağlıklı", plant: "Soya", healthy: true },
  "Squash___Powdery_mildew": { tr: "Kabak Külleme Hastalığı", plant: "Kabak", healthy: false },
  "Strawberry___Leaf_scorch": { tr: "Çilek Yaprak Yanıklığı", plant: "Çilek", healthy: false },
  "Strawberry___healthy": { tr: "Sağlıklı", plant: "Çilek", healthy: true },
  "Tomato___Bacterial_spot": { tr: "Domates Bakteriyel Leke", plant: "Domates", healthy: false },
  "Tomato___Early_blight": { tr: "Domates Erken Yanıklık", plant: "Domates", healthy: false },
  "Tomato___Late_blight": { tr: "Domates Geç Yanıklık", plant: "Domates", healthy: false },
  "Tomato___Leaf_Mold": { tr: "Domates Yaprak Küfü", plant: "Domates", healthy: false },
  "Tomato___Septoria_leaf_spot": { tr: "Domates Septoria Yaprak Lekesi", plant: "Domates", healthy: false },
  "Tomato___Spider_mites Two-spotted_spider_mite": { tr: "Domates Kırmızı Örümcek Zararı", plant: "Domates", healthy: false },
  "Tomato___Target_Spot": { tr: "Domates Hedef Leke Hastalığı", plant: "Domates", healthy: false },
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": { tr: "Domates Sarı Yaprak Kıvırcıklığı Virüsü", plant: "Domates", healthy: false },
  "Tomato___Tomato_mosaic_virus": { tr: "Domates Mozaik Virüsü", plant: "Domates", healthy: false },
  "Tomato___healthy": { tr: "Sağlıklı", plant: "Domates", healthy: true },
};

export const PLANTVILLAGE_CLASS_LIST = Object.keys(PLANTVILLAGE_CLASSES_TR);
